security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            
    providers:
        database_provider:
            entity:
                class: App\Entity\User
                property: email
                
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false        
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /course/
                username_parameter: _email
            logout:
                path: /logout
                target: /login                
            provider: database_provider
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }