# security routes
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

# user routes
user_register:
    path: /user/register
    controller: App\Controller\SecurityController::registerUser
    
test:
    path: /test
    controller: App\Controller\TestController::test    
