# security routes
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

# user routes
user_register:
    path: /user/register
    controller: App\Controller\SecurityController::registerUser

# course routes    
course_index:
    path: /course/
    controller: App\Controller\CourseController::index    
    
course_view:
    path: /course/{courseId}
    controller: App\Controller\CourseController::view
    requirements:
        course_id: \d+
